[package]
name = "logz"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde_json = "*"
flate2 = "*"

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.reqwest]
version = "*"
features = ["blocking"]
